baseball Game
ingyuseong/java-baseball-precourse pull request #3
Opened 2021-01-31 03:52 UTC by wansoo05

2021-02-03 09:53 UTC, boh97 commented on src/main/java/baseball/GamePlay.java
> +        String input = scanner.nextLine();
이것도 좋은 방법이지만 내 주관적인 생각으론 좀더 직관적이게(?) int형으로 받고 메서드에서 int값에 따른 if문을 써서 구현하는건 어떨까한다

2021-02-03 09:53 UTC, boh97 commented on src/main/java/baseball/Computer.java
> +        }
난수 만드는 메서드를 String으로 구현해 코드를 축약시킨건 좋은 아이디어인 것 같다 :)

2021-02-03 09:53 UTC, boh97 commented on src/main/java/baseball/GamePlay.java
> +    }
생성자 매개변수에 Scanner를 받는것도 코드 축약시키기에 좋아보이지만 Gameplay클래스안의 멤버 변수로 Scanner scanner를 생성해 각 메서드에서 써도 괜찮을 것 같단 생각이 든다 :)

2021-02-06 16:29 UTC, staycozyboy requested changes
음.. 일단 여러가지 개선점을 많이 남겨뒀는데, 기본적으로 요구사항대로 동작하는 소스맞나요..? 제가 보기에는 여러가지 미구현된 부분이 보입니다.

여러가지 패턴도 있고, 많이 노력한 부분은 확실히 보입니다.

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/baseball/Computer.java
> +public class Computer{
Computer라는 클래스 naming이 이 클래스가 어떤 일을 하는지 명시적으로 나타내고 있지 않은것 같습니다

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/baseball/Application.java
>          final Scanner scanner = new Scanner(System.in);
Scanner를 main 클래스에서 만들고 파라미터로 넘긴 이유가 뭔가요?

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/baseball/GamePlay.java
> +    }
앞서 main에서도 언급했지만, 어떤 의도인지 잘 모르겠습니다.

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/baseball/Player.java
> +    }
1. 일단 클래스 명과 실제 클래스의 동작이 일치하지 않는 것 같습니다.
2. `isValidNumber` 또한 함수명과 실제 함수의 동작이 일치하지 않습니다.
3. 추가적으로 `isValidNumber`을 에러를 raise해서 핸들링을 어떻게 했나보려고 어디서 호출했는지 찾아봤는데, 아예 사용하지 않은 메소드네요. 확인안해봤는데 요구사항대로 제대로 동작하는 소스인가요..? 

함수, 클래스명 naming에 관해서 구글링해보시면 도움될 것 같습니다 :)

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/utils/ComparisonUtils.java
> +public class ComparisonUtils {
싱글톤을 의도하신 거면 인스턴스 생성을 못하게 막아두는게 좋을 것 같습니다~

2021-02-06 16:29 UTC, staycozyboy commented on src/main/java/utils/ComparisonUtils.java
> +        return ball - countStrike(computerNumber, playerNumber);
연산이 중복되어 수행되고 있습니다. 물론 길이가 3이라 별 문제는 안되지만, 개선하면 더 좋을 것 같네요.

2021-02-07 05:49 UTC, wansoo05 commented on src/main/java/baseball/Application.java
>          final Scanner scanner = new Scanner(System.in);
scanner를 new를 한번만하여 메모리공간을 최소화 시키고 scanner를 사용하는 다른 클래스는 참조만 하는식으로 하려고한 의도였습니다.

2021-02-07 05:55 UTC, wansoo05 commented on src/main/java/baseball/Player.java
> +    }
1.  수정해야할것같습니다
2. 함수명도 수정해야할것같습니다
3. isValidNumber메서드는 GamePlay클래스에서 playGame메서드에서 사용됐으며,try catch문으로 에러 받아서 다시 입력 받는식으로 했습니다.

2021-02-07 05:55 UTC, wansoo05 commented on src/main/java/utils/ComparisonUtils.java
> +public class ComparisonUtils {
넵!!

2021-02-07 05:55 UTC, wansoo05 commented on src/main/java/utils/ComparisonUtils.java
> +        return ball - countStrike(computerNumber, playerNumber);
리팩토링하겠습니다

2021-02-07 07:19 UTC, wansoo05 commented on src/main/java/baseball/GamePlay.java
> +        String input = scanner.nextLine();
좋은 의견 감사합니다

2021-02-07 08:21 UTC, closed without merging